### PR TITLE
Preview2

### PR DESCRIPTION
**Pull request by ryanbrandenburg**

### CODE REVIEW

**Comment by natemcmaster** [comment]
I thought @pranavkm was doing this on all our repos...

**Comment by natemcmaster** [comment]
Looks like it's done already: https://github.com/aspnet/BrowserLink/commit/bce71cfea03b18e2d7f6ae75e656a2f6fb62f576

**Comment by ryanbrandenburg** [comment]
When I asked him if I should do it he said yes. Maybe he misunderstood my ask?

**Comment by ryanbrandenburg** [comment]
Closing since @pranavkm already did it.

**Comment by pranavkm** [comment]
Sorry, I was working through issues in my script with some respos when @ryanbrandenburg asked. I didn't realize I had already pushed to a subsection of repos by then 😢

**Pull request closed without merging**
